### ISSUE TITLE
add MAINTAINERS

### ISSUE THREAD

**Issue by liangchenye** [opencontainers/ocitools#22]
I think we can have a MAINTAINERS list on test/tooling project just like runc/specs.
I mentioned this on the TOB mailing list but seems no feedback from TOB members.
So maybe we discuss this just inside this project? @mrunalp

**Comment by mrunalp** [comment]
@liangchenye Yes, it makes sense.

**Comment by liangchenye** [comment]
I created a PR to add a `MAINTAINERS` file
https://github.com/opencontainers/ocitools/pull/23
I'm glad to be one of the maintainers.
