### ISSUE TITLE
poststop entry in ocitools-generate(1) says "before the container process is destroyed"

### ISSUE THREAD

**Issue by wking** [opencontainers/ocitools#41]
See [here][1], with language from #33.  The language looks like it's drifting towards the in-flight opencontainers/runtime-spec#395.  But however that PR goes down, the container *process* is gone by the time the post-stop hooks run, because that process existing is [the stop event][2].  I'd suggest echoing the spec:

> The post-stop hooks are called after the container process is stopped.

although I'd be a bit happier if the spec used “exits” instead of “is stopped” (to avoid confusion with `SIGSTOP`).

[1]: https://github.com/opencontainers/ocitools/blame/b31bc931d1d50fb7d606e10d56065848e8ba4f26/man/ocitools-generate.1.md#L138-L140
[2]: https://github.com/opencontainers/runtime-spec/blob/v0.5.0/config.md#poststop

**Comment by liangchenye** [comment]
+1, I think we would better synchronize the language used in ocitools with oci spec.

**Comment by mrunalp** [comment]
Yeah, we can change the man page.
