### ISSUE TITLE
Unexpected capability audit_read set for process

### ISSUE THREAD

**Issue by liangchenye** [opencontainers/ocitools#63]
Hi Mrunal,
I test runc today and find it fails in the process validation.
The reason seems it adds an extra 'audit_read' capability which is not defined in the config.json. 
It is not clear in the runtime spec that extra configs should taken as an error and we don't check the unexpected environment variables in the environment validation.
So maybe it does not necessary to popup an 'Unexpected capability' error? @mrunalp

**Comment by wking** [comment]
On Tue, May 10, 2016 at 01:24:01AM -0700, 梁辰晔 (Liang Chenye) wrote:
> It is not clear in the runtime spec that extra configs should taken
> as an error and we don't check the unexpected environment variables
> in the environment validation.

If runtimes are allowed to inject capabilities and environment
variables, I think the spec should explicitly grant them that power.
Especially for capabilities, it seems like the runtime should avoid
granting powers that the config does not call for.

**Comment by mrunalp** [comment]
I think that the runtime should fail if it can't apply a certain configuration value.

**Comment by wking** [comment]
On Tue, May 17, 2016 at 03:45:29PM -0700, Mrunal Patel wrote:
> I think that the runtime should fail if it can't apply a certain
> configuration value.

And just to be clear, injecting an extra capability falls under “can't
apply”?  I wouldn't be surprised if runC does a number of things that
aren't covered by the spec in an attempt to be helpful and/or support
Docker.  I'd rather have that sort of thing (if it happens) encoded in
the runtime spec with and opt-in/out.
