### ISSUE TITLE
Where do we enforce UTF-8 JSON?

### ISSUE THREAD

**Issue by wking** [opencontainers/ocitools#67]
Spun off from #66, where “All configuration JSON MUST be encoded in UTF-8” is checked.  And it seems to be:

    $ ./ocitools generate
    $ iconv -f UTF-8 -t UTF-16 config.json -o config-16.json
    $ mv config-16.json config.json
    $ file config.json
    config.json: Little-endian UTF-16 Unicode text
    $ ./ocitools validate --path .
    FATA[0000] invalid character 'ÿ' looking for beginning of value

But I can't find [Go docs on what input encodings are supported][1] or UTF references in ocitools:

    $ git grep -i utf origin/master
    Binary file origin/master:rootfs.tar.gz matches

The Go docs [reference RFC 4627][1], and the RFC [explains how to detect the encoding][2], but maybe Go doesn't support that yet?  Can someone with more Go+JSON experience explain how this works?

[1]: https://golang.org/pkg/encoding/json/
[2]: https://tools.ietf.org/html/rfc4627#section-3

**Comment by liangchenye** [comment]
@wking my mistake, I just update #66, ocitools has not verify utf8 encoding yet.
I test it locally by using https://golang.org/pkg/unicode/utf8/#Valid. It works well.

In my test, I add a Chinese word  "/主目录" to CWD field in config.json and convert it to gb18030.
utf8.Valid returns false.
