### ISSUE TITLE
[ReadMe] Link to man pages from ReadMe

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/ocitools#68]
It looks like @rhatdan has started on some documentation in a /man folder.  It would be good to link to this from the ReadMe

**Comment by wking** [comment]
On Mon, May 16, 2016 at 12:35:10PM -0700, Rob Dolin (MSFT) wrote:
> It looks like @rhatdan has started on some documentation in a /man
> folder.  It would be good to link to this from the ReadMe

We already do since ba4a9a04e (README: Punt detailed command
description to the man pages, 2016-04-27, #47).  Do the links need to
be more obvious?

**Comment by RobDolinMS** [comment]
Thanks @wking.  I see these now.
