### ISSUE TITLE
Should the `--path` option of `ocitools validate` have a default value?

### ISSUE THREAD

**Issue by hmeng-19** [opencontainers/ocitools#91]
Currently, calling `ocitools validate` without specifying `--path` option would fail:

    [hmeng@localhost test]$ ocitools validate 
    FATA[0000] Bundle path shouldn't be empty  

I am thinking whether we should have a default value for the `--path` option of `ocitools validate`, the default value can be `.` (the current working dir).
This makes calling `ocitools validate` and `ocitools generate` consistent, also saves some typing.

**Comment by wking** [comment]
On Thu, Jun 02, 2016 at 05:17:01PM -0700, hmeng-19 wrote:
> I am thinking whether we should have a default value for the
> `--path` option of `ocitools validate`, the default value can be `.`
> (the current working dir).

Sounds good to me.

**Comment by rhatdan** [comment]
SGTM

**Comment by mrunalp** [comment]
:+1:

**Comment by liangchenye** [comment]
PR checked in. This issue could be close now :)   @mrunalp  @hmeng-19

**Comment by hmeng-19** [comment]
Fixed by #92 .
